name: Deploy Main Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Build game
        run: npm run dendrynexus make-html -- --pretty
      - name: Copy game.json to output
        run: cp out/game.json out/html/
      - name: Deploy to gh-pages root
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out/html
          branch: gh-pages
          clean-exclude: dev
